### ISSUE TITLE
Transfer large file implementation issues

### ISSUE THREAD

**Issue by 10045125** [akshetpandey/react-native-cronet#2]
I read the implementation of your Cronet in OkHttp. When the data is read, the data is read into the memory at one time. Is this a problem for large files?

**Comment by akshetpandey** [comment]
That is definitely an issues, but as far as I can tell, react-native also behaves in a similar way, since all the bytes are kept in memory and then transferred to JS when the bytes are requested. There is no concept of writing straight to a file in react-native.

**Comment by 10045125** [comment]
Cronet is integrated in OKhttp. What do you need to do with the file type? Can you open up the implementation of integrating Cronet into OkHttp?

**Comment by akshetpandey** [comment]
Cronet source code is available here: https://chromium.googlesource.com/chromium/src/+/HEAD/components/cronet/

I am not sure what you mean by Cronet is integrated in OkHttp. I am also not sure what do you mean by file type, but what I meant was that there is no concept of streaming bytes in react-native, except when dealing with images using fresco (using an <Image /> in react-native).
